CATEGORY_MAPPER = {
	'Aligned Multiwall CNTs': 'Aligned MWCNT',
	'Aligned Few-wall CNTs': 'Aligned FWCNT',
	'Unaligned Few-wall CNTs': 'Unaligned FWCNT',
	'GIC': 'Other Carbons',
	'Individual Multiwall CNTs': 'Individual Structures',
	'Conductive Polymer': 'Other Carbons',
	'Carbon Fiber': 'Other Carbons',
	'Individual FWCNT': 'Individual Structures',
	'Metal': 'Other',
	'Unaligned multiwall CNTs': 'Unaligned MWCNT',
	'Individual Bundle': 'Individual Structures',
	'Metal CNT Composite': 'Other',
	'Single crystal graphite': 'Individual Structures',
	'Synthetic fiber': 'Other',
	'Graphene Nanoribbon': 'Other',
	'Paper': 'Other',
	'Amorphous carbon': 'Other',
	'Glassy Carbon': 'Other',
	'Mott minimum conductivity': 'Other',
	'Superconductor': 'Other',
	'Diamond': 'Other',
}
